spring:
  config:
    activate:
      on-profile: "oauth"

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-key: ${KAKAO_CLIENT_KEY}
  redirect-uri: ${KAKAO_REDIRECT_URI}

apple:
  client-id: ${APPLE_CLIENT_ID}
