spring:
  profiles:
    group:
      dev: "dev, mysql, firebase"
      test: "h2"
    include:
      - swagger
      - oauth
      - jwt

  application:
    name: wini
  config:
    import: optional:file:.env[.properties]
